services:
  frontend:
    build:
      context: ./Learner_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Learner_frontend:/app
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  api:
    build: 
      context: ./Learner_backend
    container_name: flask_api
    environment:
      - FLASK_APP=/app/Learner_backend/run.py
      - FLASK_ENV=development
    ports:
      - "${API_PORT}"
    volumes:
      - ./Learner_backend:/app
      # from https://stackoverflow.com/questions/40961073/starting-and-stopping-docker-container-from-other-container
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - frontend
    

  # from https://community.cloudflare.com/t/can-i-use-cloudflared-in-a-docker-compose-yml/407168
  #tunnel:
    #container_name: cloudflared-tunnel
    #image: cloudflare/cloudflared
    #restart: unless-stopped
    #command: tunnel run
    #environment:
      #- TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}

networks:
  default:
    name: learner_network